name: Sync with Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily, adjust as needed

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sync with upstream
        run: |
          git remote add upstream <upstream_repository_url>
          git fetch upstream
          git merge upstream/main  # or use the branch you want to sync
          git push



          